export const DROPDOWN_OPTIONS = {
  MEASUREMENT_UNITS: [
    { label: 'Kilogram (kg)', value: 'kg' },
    { label: 'Liter (L)', value: 'l' },
    { label: 'Piece (pcs)', value: 'pcs' },
    { label: 'Meter (m)', value: 'm' },
    { label: 'Box (box)', value: 'box' },
    { label: 'Pack (pack)', value: 'pack' },
    { label: 'Dozen (doz)', value: 'doz' },
    { label: 'Gram (g)', value: 'g' },
    { label: 'Ton (t)', value: 't' },
    { label: 'Barrel (bbl)', value: 'bbl' },
  ],
  PRODUCT_NATURE: [
    { label: 'For Sale', value: 'for_sale' },
    { label: 'For Office Use', value: 'for_office_use' },
    { label: 'For Delivery', value: 'for_delivery' },
    { label: 'For Packaging', value: 'for_packaging' },
    { label: 'For Storage', value: 'for_storage' },
    { label: 'For Maintenance', value: 'for_maintenance' },
    { label: 'For Personal Use', value: 'for_personal_use' },
    { label: 'For Promotion', value: 'for_promotion' },
  ],
  NATURE_OF_ASSET: [
    { label: 'Tangible', value: 'tangible' },
    { label: 'Consumable', value: 'consumable' },
    { label: 'Fixed Asset', value: 'fixed_asset' },
    { label: 'Current Asset', value: 'current_asset' },
    { label: 'Intangible Asset', value: 'intangible_asset' },
    { label: 'Inventory', value: 'inventory' },
    { label: 'Depreciable', value: 'depreciable' },
    { label: 'Non-depreciable', value: 'non_depreciable' },
  ],
  SOURCE_TYPES: [
    { label: 'Supplier', value: 'supplier' },
    { label: 'Dealer', value: 'dealer' },
  ],
  STORAGE_TYPES: [
    { label: 'Pallet Storage', value: 'pallet' },
    { label: 'Shelf Storage', value: 'shelf' },
    { label: 'Bin Storage', value: 'bin' },
    { label: 'Bulk Storage', value: 'bulk' },
    { label: 'Cold Storage', value: 'cold' },
    { label: 'Rack Storage', value: 'rack' },
    { label: 'Drive-In Rack Storage', value: 'drive_in_rack' },
    { label: 'Drawer Storage', value: 'drawer' },
    { label: 'Secure Vaults', value: 'secure_vaults' },
  ],
};
