import { TableConfig } from '@app/core/interfaces/table';

export const INVENTORY_OVERVIEW_TABLE_CONFIG: TableConfig = {
    title: 'Inventory Overview',
    cardColumnsDesktop: 3,
    columns: [
        {
            source: 'product_name',
            label: 'Product',
            width: '15%',
            alignment: 'left',
            filterable: true,
            column_type: 'text',
        },
        {
            source: 'total_available_quantity',
            label: 'Available Stock',
            width: '10%',
            alignment: 'left',
            filterable: true,
            column_type: 'text',
        },
        {
            source: 'total_batches',
            label: 'Batches',
            width: '8%',
            alignment: 'left',
            filterable: true,
            column_type: 'text',
        },
        {
            source: 'restock_threshold',
            label: 'Restock At',
            width: '8%',
            alignment: 'left',
            filterable: false,
            column_type: 'text',
        },
        {
            source: 'inventory_status',
            label: 'Inventory Status',
            width: '8%',
            alignment: 'left',
            filterable: false,
            column_type: 'status',
            text_color: [
                { name: 'Ready for Sale', color: '#109648', icon: 'check' },
                { name: 'Pending Pricing', color: '#7C3AED', icon: 'warning' },
                { name: 'Internal Use', color: '#64748B', icon: 'info' },
            ],
        },
        {
            source: 'stock_alert',
            label: 'Stock Alert',
            width: '8%',
            alignment: 'center',
            filterable: false,
            column_type: 'status',
            text_color: [
                { name: 'Low Stock', color: '#DF2935', icon: 'warning' },
                { name: 'OK', color: '#109648', icon: 'check' },
            ],
        },
        {
            source: 'total_stock_cost',
            label: 'Stock Cost',
            width: '10%',
            alignment: 'left',
            filterable: true,
            column_type: 'currency',
            currency: 'BDT',
            locale: 'en-IN',
        },
        {
            source: 'expected_revenue',
            label: 'Expected Revenue',
            width: '10%',
            alignment: 'left',
            filterable: true,
            column_type: 'currency',
            currency: 'BDT',
            locale: 'en-IN',
        },
        {
            source: 'potential_profit',
            label: 'Potential Profit',
            width: '10%',
            alignment: 'left',
            filterable: true,
            column_type: 'currency',
            currency: 'BDT',
            locale: 'en-IN',
        },
        {
            label: 'Actions',
            width: '8%',
            alignment: 'right',
            column_type: 'action',
            actions: [{ action: 'view', label: 'View', icon: 'eye' }],
        },
    ],
    pageSizeOptions: [10, 20, 30, 50],
    defaultPageSize: 10,
    noData: {
        message: 'No products with active inventory found. Products appear here once they have been purchased and verified.',
    },
};
